
<link rel="stylesheet" type="text/css" title="Main" media="screen,print" href="<?php if(isset($durum)){echo '../../kodlar/yan_teststil.css';}else{echo '../kodlar/yan_teststil.css';} ?>" />
<div class="yan_test_modulu">
 <a class="menu_link" href="<?php if(isset($durum)){echo '../../testler';}else{echo '../testler';} ?>" title="Bilgilerinizi test edin..."><h4 class="yanbaslik_test">Gerçekten İyi Misin? </h4></a>
 <a class="menu_link" href="<?php if(isset($durum)){echo '../../testler/html_testi-t1.html';}else{echo '../testler/html_testi-t1.html';} ?>" title="html5 bilgilerinizi test edin..."><img src="<?php if(isset($durum)){echo '../../img/html5.png';}else{echo '../img/html5.png';}?>" width="40" height="35" alt="html5 simgesi" style="float:right;padding-top:3px" /><h3 class="dikkatceken">HTML5 testimize katılın...</h3></a>
 <a class="menu_link" href="<?php if(isset($durum)){echo '../../testler/css3_testi-t2.html';}else{echo '../testler/css3_testi-t2.html';} ?>" title="css3 bilgilerinizi test edin..."><img src="<?php if(isset($durum)){echo '../../img/css3.png';}else{echo '../img/css3.png';}?>" width="30" height="35" alt="css3 simgesi" style="float:right;padding-right:5px;margin-top:-10px" /><h3 class="dikkatceken">CSS3 testimize katılın...</h3></a>
 <a class="menu_link" href="<?php if(isset($durum)){echo '../../testler/php_testi-t3.html';}else{echo '../testler/php_testi-t3.html';} ?>" title="php bilgilerinizi test edin..."><img src="<?php if(isset($durum)){echo '../../img/php.png';}else{echo '../img/php.png';}?>" width="30" height="20" alt="php simgesi" style="float:right;padding-right:5px;margin-top:-5px" /><h3 class="dikkatceken">PHP testimize katılın...</h3></a>
 <a class="menu_link" href="<?php if(isset($durum)){echo '../../testler/javascript_testi-t4.html';}else{echo '../testler/javascript_testi-t4.html';} ?>" title="javascript bilgilerinizi test edin..."><img src="<?php if(isset($durum)){echo '../../img/javascript.png';}else{echo '../img/javascript.png';}?>" alt="javascript simgesi" width="30" height="35" style="float:right;padding-right:5px;margin-top:-10px" /><h3 class="dikkatceken">JAVASCRİPT testimize katılın...</h3></a>
 <a class="menu_link" href="<?php if(isset($durum)){echo '../../testler/sql_testi-t5.html';}else{echo '../testler/sql_testi-t5.html';} ?>" title="sql bilgilerinizi test edin..."><img src="<?php if(isset($durum)){echo '../../img/sql.png';}else{echo '../img/sql.png';}?>" width="30" height="35" alt="sql simgesi" style="float:right;padding-right:5px;margin-top:-10px" /><h3 class="dikkatceken">SQL testimize katılın...</h3></a>
 <a class="menu_link" href="<?php if(isset($durum)){echo '../../testler/programlama_testi-t6.html';}else{echo '../testler/programlama_testi-t6.html';} ?>" title="genel programlama bilginizi test edin..."><img src="<?php if(isset($durum)){echo '../../img/algoritma.svg';}else{echo '../img/algoritma.svg';}?>" alt="algoritma simgesi" width="30" height="35" style="float:right;padding-right:5px;margin-top:-10px" /><h3 class="dikkatceken">Genel Programlama testimize katılın...</h3></a>
</div> 
